name: Deploy to Firebase

on:
  push:
    branches:
      - main # Triggers on direct pushes/merges to main
      - dev  # Triggers on direct pushes/merges to dev
  pull_request: # Add this section
    branches:
      - dev  # Triggers when a PR is opened/updated targeting the dev branch
    types: [opened, synchronize, reopened] # Specify PR event types

jobs:
  deploy_firebase:
    runs-on: ubuntu-latest
    env:
      FIREBASE_PROJECT_ID_PROD: koffee-karma
      FIREBASE_PROJECT_ID_DEV: koffee-karma-dev
      # Path where the service account key will be written
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/serviceAccountKey.json

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install function dependencies
        run: npm ci
        working-directory: ./functions

      # Deploy to DEV environment (handles both PR to dev and push to dev)
      - name: Deploy to Firebase (Dev)
        if: (github.event_name == 'pull_request' && github.base_ref == 'dev') || (github.event_name == 'push' && github.ref == 'refs/heads/dev')
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/serviceAccountKey.json
        run: |
          echo "Attempting to write DEV service account key to ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          echo "${{ secrets.FIREBASE_SA_DEV }}" > ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          
          echo "Verifying DEV service account key file..."
          ls -l ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          if [ ! -s ${{ env.GOOGLE_APPLICATION_CREDENTIALS }} ]; then
            echo "Error: DEV Service account key file is empty or does not exist."
            exit 1
          fi
          echo "DEV Service account key file exists and is not empty. First line:"
          head -n 1 ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          
          echo "Exporting GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          export GOOGLE_APPLICATION_CREDENTIALS="${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          
          echo "Attempting logout (should indicate not logged in)..."
          firebase logout
          
          echo "Verifying Firebase CLI authentication with service account..."
          firebase projects:list
          
          echo "Verifying gcloud CLI authentication with service account (if gcloud is available)..."
          gcloud auth list || echo "gcloud CLI not available or not authenticated"
          
          echo "Attempting to deploy to DEV project: ${{ env.FIREBASE_PROJECT_ID_DEV }}"
          firebase deploy --only functions --project ${{ env.FIREBASE_PROJECT_ID_DEV }} --non-interactive --force

      # Deploy to PROD environment (handles push to main)
      - name: Deploy to Firebase (Prod)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/serviceAccountKey.json
        run: |
          echo "Attempting to write PROD service account key to ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          echo "${{ secrets.FIREBASE_SA_PROD }}" > ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}

          echo "Verifying PROD service account key file..."
          ls -l ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          if [ ! -s ${{ env.GOOGLE_APPLICATION_CREDENTIALS }} ]; then
            echo "Error: PROD Service account key file is empty or does not exist."
            exit 1
          fi
          echo "PROD Service account key file exists and is not empty. First line:"
          head -n 1 ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
          
          echo "Exporting GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          export GOOGLE_APPLICATION_CREDENTIALS="${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          
          echo "Attempting logout (should indicate not logged in)..."
          firebase logout
          
          echo "Verifying Firebase CLI authentication with service account..."
          firebase projects:list

          echo "Verifying gcloud CLI authentication with service account (if gcloud is available)..."
          gcloud auth list || echo "gcloud CLI not available or not authenticated"
          
          echo "Attempting to deploy to PROD project: ${{ env.FIREBASE_PROJECT_ID_PROD }}"
          firebase deploy --only functions --project ${{ env.FIREBASE_PROJECT_ID_PROD }} --non-interactive --force
      
      - name: Cleanup Service Account Key
        if: always() # Ensures this step runs even if previous steps fail
        run: rm -f ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}